backend/models/Document.php
<?php

namespace backend\models;


use yii;

class Document extends \common\models\Document 
{
	


}

backend/models/DocumentType.php
<?php

namespace backend\models;
use Yii;

/**
 * This is the model class for table "adr_document_types".
 *
 * @property integer $id
 * @property string $name
 *
 * @property Document[] $documents
 */
class DocumentType extends \common\models\DocumentType
{

}

common/models/DocumentType.php
<?php
/* генерируемый файл, редактировать его не надо */


namespace common\models;


use yii;
use yii\helpers\ArrayHelper;



/**
 * This is the model class for table "adr_document_types".
 *
 * @property integer $id
 * @property string $name
 * @property string $template
 * @property string $alias
 *
 * @property Document[] $documents
 */
class DocumentType extends \common\models\EntityExt 
{
	
	
	
	
    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'adr_document_types'; 
    }



    public static function parentClassName(){
		return '\common\models\CObject';
    }



	/* Списки для перечисляемых типов атрибутов */
	public static function attrLists() {
		return [

		];
	}
	/* Метаданные класса */
	public static function meta() {
		return [
			'title' => 'Типы документов', 
			'imp' => 'Тип документа', 
			'rodp' => 'Типа документа', 
			'vinp' => 'Тип документа', 
			'model' => 'DocumentType', 
			'parent' => 'objects', 
			'sortattr' => 'name', 
			'sortdir' => 'asc', 
			'caption' => '%name%', 
				
		];
	}
	/* Метаданные атрибутов*/
	public static function attrMeta() {
			$parentAttrMeta = [];
			if (self::parentClassName()) {
				$parentAttrMeta = self::parentClassName()::attrMeta();
			};

			return ArrayHelper::merge(		
				$parentAttrMeta,
				[
								'id' => ['label' => 'ID', 'readonly' => '1', 'type' => 'integer', 'required' => '1', 'show' => '0', 'visible' => '0', ], 
			'name' => ['label' => 'Название', 'comment' => 'Человеко понятное название типа документа', 'type' => 'string', 'required' => '1', 'show' => '1', 'visible' => '1', ], 
			'template' => ['label' => 'Шаблон', 'comment' => 'Шаблон для генерации документа в pdf', 'show' => '0', 'readonly' => '1', 'type' => 'text', 'required' => '0', 'visible' => '0', ], 
			'alias' => ['label' => 'Псевдоним', 'comment' => 'Внутренне имя типа документа для привязки ее к участию в бизнес-логике', 'visible' => '1', 'readonly' => '0', 'type' => 'string', 'required' => '1', 'show' => '1', ], 

						
				]
			);
		}
		/* Поведения*/
	public function behaviors(){
	
	$result = [];
		$ns = "common\models\\";	
		$class = $ns.$this -> meta()['model'].'Behavior';
		
		if (class_exists($class)) {
			$result['ext'] = [
				'class' => $class,
			];
		};
	
		return $result;
		
		
}
	

	// Создать объект по указанному псевдониму, если такой псевдоним существует.
	public static function byAlias($value) 
	{
		return self::findOne(['alias' => $value]);
	}







    /**
     * @inheritdoc
     */
    public function rules()
    {
        return array_merge(parent::rules(), [
            [['id', 'name', 'alias'], 'required'],
            [['id'], 'integer'],
            [['template'], 'string'],
            [['name'], 'string', 'max' => 50],
            [['alias'], 'string', 'max' => 45],
            [['id'], 'unique'],
            [['alias'], 'unique'],
        ]);
    }
	

	
	
	
	
    

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDocuments() {
        return $this->hasMany(Document::className(), ['doc_type_id' => 'id']);
    }



    public static function captionTemplate(){

        return "%name%";
    }





}

frontend/models/Document.php
<?php

namespace frontend\models;

use Yii;
use yii\web\View;


class Document extends \common\models\Document
{

    /**
     * @param int $documentId
     * @return mixed
     */
    public static function getPdfDocument(int $documentId)
    {
        $document = self::findOne($documentId);
        $view = new View();

        $mpdf = Yii::$app->pdf->api;
        $mpdf->WriteHtml($view->render('/documents/sb-bank.php'));
        return $mpdf->Output();
    }
}

frontend/models/DocumentType.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "adr_document_types".
 *
 * @property integer $id
 * @property string $name
 *
 * @property Document[] $documents
 */
class DocumentType extends \common\models\DocumentType
{

}

backend/controllers/DocumentController.php
<?php
/* генерируемый файл, редактировать его не надо */


namespace backend\controllers;

use Yii;
use backend\models\Document;
use common\models\DocumentSearch;
use backend\controllers\BasicController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * DocumentController implements the CRUD actions for Document model.
 */
class DocumentController extends BasicController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Document models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DocumentSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Document model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Document model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Document();
		
		if (Yii::$app->request->get() && isset(Yii::$app->request->get()['data'])) {
				$data = Yii::$app->request->get()['data'];
				$model->load($data, '');
				$model->integrate();
		};


        if ($model->load(Yii::$app->request->post()) && $model->save()) {		
			Yii::$app->session->setFlash('success', "Данные Документа сохранены");
            return $this->redirect(['update', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Document model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
		$tab = isset($_GET['tab'])?$_GET['tab']:false;
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {           
			if ($model->save()) {                       
				Yii::$app->session->setFlash('success', "Данные Документа сохранены");
				//return $this->redirect(['view', 'id' => $model->id]);
			}
		};
           
           
		return $this->render('update', [
			'model' => $model,
			'tab' => $tab               
		]);
    }

    /**
     * Deletes an existing Document model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Document model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Document the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Document::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('Запрашиваемая страница не найдена.');
        }
    }
}

frontend/controllers/DocumentController.php
<?php

namespace frontend\controllers;

use Yii;

use common\models\Entity;
use common\models\EntityExt;
use common\models\PayManager;
use common\models\SettlementSearch;
use common\models\PaymentSearch;
use frontend\models\Document;
use frontend\models\Invoice;
use frontend\models\Payment;
use frontend\models\User;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;


class DocumentController extends BasicController
{
	
	const UC_CUSTOMER = 'customer';
	const UC_OWNER = 'owner';
	
	public $cabinet;

	public static function getCabinet() {
		$result = 'main';
		$cuser = User::getCurrentUser();
		if ($cuser) {
			if ($cuser -> checkrole(User::ROLE_CUSTOMER)) return self::UC_CUSTOMER;
			if ($cuser -> checkrole(User::ROLE_OWNER)) return self::UC_OWNER;
		};
		return $result;
	}
	
	
	
	// Сюда направляется платежная система после совершения оплаты по карте.
	// Здесь создается объект оплаты (Payment), изменяется статус заказа
	public function actionPayBack($orderId) {
		if (!User::getCurrentUser()) throw new ForbiddenHttpException('Страница не доступна для незарегистрированного пользователя');
		$this -> layout = self::getCabinet().'.php';
		$payId = $orderId;		
		$payment = Payment::findOne(['pay_id' => $payId]);
		if (is_null($payment)) {
			throw new \Exception('Попытка проведения некорректного платежа');
		}		
		
		if ($payment -> confirmed) {
			//throw new NotFoundHttpException('Попытка дублирования оплаты по карте');
		}

		//проверка статуса заказа
        $payCheck=PayManager::payCheck([
            'id'=>$payment->pay_id,
            'number'=>$payment->id
        ]);
        if(!$payCheck['actionCode']) {
            $payment->confirmed = 1; // Подтверждаем платеж, без этого флажка оплата считается не проведенной!
            $payment->save();
            $payment->invoice->balance(); // счет сам проверяет все платежи и выставляет себе состояние оплачен или нет
            $payMessage='Счет '.$payment->id.' оплачен успешно';
            $payStatus=true;
        }else{
            $payMessage='Ошибка оплаты: '.$payCheck['errorMessage'];
            $payStatus=false;
        }
		Yii::$app -> eventManager -> callEvent('afterPayment', ['payment' => $payment]); 
		
		return $this->render('paid', [
            'payment' => $payment,
            'payStatus'=>$payStatus,
            'message'=>$payMessage
        ]);
		
	}
	
	public function actionPayFail($orderId) {
		echo "PayFail";
		var_dump($orderId); 
	}
	
	
	
	// оплата по счету c $id
	public function actionPay($id) {
		if (!User::getCurrentUser()) throw new ForbiddenHttpException('Страница не доступна для незарегистрированного пользователя');
		$model = Document::findOne($id);
		
		if (is_null($model)) throw new NotFoundHttpException('Счет не найден id='.$id);
		if ($model -> state == Invoice::STATE_PAID) throw new NotFoundHttpException('Счет №'.$model -> number.' уже оплачен ');
		$amount = $model -> summa;		
		// Создаем оплату
		$payment = new Payment();
		$payment -> ptype = Payment::PTYPE_CARD;
		$payment -> value = $amount;
		$payment -> invoice_id = $id;
		$payment -> save();
		$number = $payment -> id;
		$result = $payment -> recipient -> payRegOrder([
			'number' => $number, 
			'amount' => $amount, 
			'returnUrl' => Url::base(true).Url::to(['/document/pay-back']),
		]);
		//echo "$number<br>";
		if (isset($result['errorCode']) && $result['errorMessage']) {
			throw new \Exception('Ошибка: ['.$result['errorCode'].'] '.$result['errorMessage']. ' №'.$number);
		} else {			
			$payId = $result['orderId'];
			$payment -> pay_id = $payId;
			$payment -> save();
				
			return $this -> redirect($result['formUrl']);
		}
	}
			
	
    public function actionSettlements()
    {
		if (!User::getCurrentUser()) throw new ForbiddenHttpException('Страница не доступна для незарегистрированного пользователя');
        $searchModel = new SettlementSearch();
        $searchModel->load(Yii::$app->request->get());
        $searchModel->recipientId = $this->getRcipients();
        $searchModel->payerId = $this->getPayers();

        //$searchModel -> load($this -> getSearchModelParams(), '');

        $dataProvider = $searchModel->search();


        return $this->render('@frontend/views/'.$this -> cabinet.'/document/settlements', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);

    }


    public function actionPsettlements()
    {
		if (!User::getCurrentUser()) throw new ForbiddenHttpException('Страница не доступна для незарегистрированного пользователя');
        $searchModel = new SettlementSearch();
        $searchModel->load(Yii::$app->request->get());
		
        //$searchModel -> load($this -> getSearchModelParams(), '');

        $user = EntityExt::portal();
        $list = array_keys($user->requisiteList());
        $searchModel->recipientId = $list;

        $searchModel->payerId = $this->getRcipients();

        $dataProvider = $searchModel->search();
        return $this->render('@frontend/views/document/psettlements', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    // Плательщик денег - Я
    public function getPayers()
    {
        $user = Entity::getCurrentUser();
        $list = array_keys($user->requisiteList());

        return $list;
    }

    // Получатель денег - кто-угодно
    public function getRcipients()
    {
        return [];
    }

    // Просмотр документа
    public function actionView($id)
    {
        $model = $this->findModel($id);
        return $this->render('@frontend/views/document/view', [
            'model' => $model,
        ]);
    }

    // Просмотр Pdf документа
    public function actionShowPdf($id)
    {
        return $this->redirect(Document::findOne($id)->getPdf());
    }



}

frontend/views/customer/document/_filter.php
<?php

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use frontend\models\Document;

use kartik\builder\Form;
use kartik\builder\FormGrid;
use kartik\widgets\ActiveForm;

use frontend\components\FilterWindow;
?>
<style>
    #settlementFilterForm .input-daterange {
        float: left;
        margin: 0;
        width: 100%;
    }
/*
#settlementsearch-datefrom {
	width: 180px;
}
#settlementsearch-dateto {
	width: 180px;
}
#settlementsearch-summa{
	width: 120px;	
}





#settlementFilterForm .input-daterange {
	float: left;
	margin: 0;
	width: 90%;
}

#settlementFilterForm .input-daterange .form-control{
		width: 100%;
}

#settlementFilterForm .form-control {
	float: left;
	
	margin: 0;
}

#settlementFilterForm input.form-control {
	width: 90%;
}

#settlementFilterForm #ordersearch-address_id {
	width: 90%;
}

#settlementFilterForm .hint-block{
	display: block;
	float: left;
	width: 90%;
}
*/


</style>

<?php


$dateRangeLayout = <<< HTML
    
    {input1}    	
    {separator}    
    {input2}
    <span class="input-group-addon kv-date-remove">
        <i class="glyphicon glyphicon-remove"></i>
    </span>
HTML;

$controls = [
		'documentTypes' => ['type'=>Form::INPUT_CHECKBOX_LIST, 'label'=> 'показать', 'items' => [1 => 'счета', 2 => 'платежи'], 'hint'=>''],
		'dateFrom' => ['type'=>Form::INPUT_WIDGET, 'widgetClass'=>'kartik\widgets\DatePicker', 'label'=>'Период: ',
		'hint'=>'дата документа', 
		'options'=>[
			'layout' => $dateRangeLayout,
			'attribute' => 'dateFrom',
			'attribute2' => 'dateTo',
			'separator' => ' - ',
			'type' => kartik\widgets\DatePicker::TYPE_RANGE,
			'pluginOptions' => [
				'todayHighlight' => true, 
				'todayBtn' => true,				
				'autoclose'=>true,   			
				'endDate' => '0d',
				'format' => 'dd.mm.yyyy'
			]
		]
	],
						
						/*
						'dateRange' => ['type'=>Form::INPUT_WIDGET, 'widgetClass'=>'\kartik\daterange\DateRangePicker', 'label'=>'Дата', 'hint'=>''],
						'dateFrom' => ['type'=>Form::INPUT_WIDGET, 'widgetClass'=>'\kartik\date\DatePicker', 'label'=>'с', 'hint'=>'', 'options'=>['type' => \kartik\date\DatePicker::TYPE_COMPONENT_APPEND, 'pluginOptions' => ['autoclose'=>true, 'format' => 'dd.mm.yyyy'], ]],
						'dateTo' => ['type'=>Form::INPUT_WIDGET, 'widgetClass'=>'\kartik\date\DatePicker', 'label'=>'по', 'hint'=>'', 'options'=>['type' => \kartik\date\DatePicker::TYPE_COMPONENT_APPEND, 'pluginOptions' => ['autoclose'=>true, 'format' => 'dd.mm.yyyy'], ]],
*/
						
		'summaCondition' => ['type'=>Form::INPUT_DROPDOWN_LIST, 'label'=> 'сумма', 'items' => [0 => '=', 1 => '<', 2 => '>'], 'options' => ['style'=>'width:60px; margin-left: 10px']],
		'summa' => ['type'=>Form::INPUT_WIDGET, 'label'=> false,  'widgetClass'=>'\yii\widgets\MaskedInput', 'options' => ['mask' => '9{1,12}',]],						
		'actions'=>['type'=>Form::INPUT_RAW, 'value'=>  Html::submitButton('Применить', ['class'=>'reg-button', 'style'=>'float: right;'])],            
];


$layout = [
[
//	'contentBefore'=>'Фильтр',
	'autoGenerateColumns' => false,
	'columns' => 1,
	'attributes' => [		
		'documentTypes' => $controls['documentTypes'],		
		
	],
],

[
	'columns' => 1,
	'attributes' => [		
		//'dateRange' => $controls['dateRange'],
		'dateFrom' => $controls['dateFrom'],		
		
	]
],

/*
[
	'columns' => 1,
	'attributes' => [		
		'dateTo' => $controls['dateTo'],
		
	]
],

*/

[
	'columns' => 2,
	'attributes' => [		
		'summaCondition' => $controls['summaCondition'],
		'summa' => $controls['summa'],
	]
],

[
	'columns' => 1,
	'attributes' => [	
		
		'actions' => $controls['actions'],
	]
]


];
	echo FilterWindow::widget(
			[
				'options' => [
					'id' => 'settlementFilterForm', 					
					'method' => 'get',
				],
				'model' => $searchModel,
				'layout' => $layout,
					
			]);

frontend/views/customer/document/settlements.php
<style>
.minus {
	color: red;
}

.plus {
	color: #007700;
}
</style>
<?php
use \kartik\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use frontend\models\Document;
use frontend\models\Invoice;
use frontend\models\Order;

use kartik\builder\Form;
use kartik\builder\FormGrid;
use kartik\widgets\ActiveForm;

$this->title = 'Расчеты';
$this->params['breadcrumbs'] =
    [

        [
            'label'     => 'Личный кабинет',
            'url'       =>  ['/customer'],
            'template'  =>  '<span class="b-link">{link}</span><span class="separate-links">\</span>'.PHP_EOL,
        ],
        [
            'label' => $this -> title,
        ],

    ];


?>


<div style="clear:both"></div>
<h1><?=$this->title?></h1>
<div class="row">
	<?=\frontend\components\FilterWindow::getFilterButton($searchModel)?>
</div>
<?php

echo GridView::widget([
    'dataProvider'=>$dataProvider,        
    'columns'=>[
//        ['class'=>'kartik\grid\SerialColumn'],
		[
            'attribute'=>'id',	
			'label' => 'No',
/*			
			'format' => 'raw',			
			'value' => function($data) {
				
				return (!$data['invoice_id'])?Html::a($data['id'], Url::to(['/'.$this -> context -> cabinet.'/document/view/'.$data['id']]), ['title' => 'Просмотреть счет']):$data['id'];
			}
*/			
			
        ],
				
		
		[
            'attribute'=>'date',			
			'label' => 'дата',
			'format' => 'datetime',
			
        ],
		
		[
            'attribute'=>'operation',			
			'label' => 'вид операции',
			'format' => 'raw',
			'value' => function($data) {
				if ($data['is_invoice']) { // Для счета указываем номер и ставим ссылку на скачивание
					$invoice = Invoice::findOne([$data['id']]);
					if ($invoice) {
						return Html::a($data['operation'].' №'.$invoice -> number, Url::to(['document/show-pdf', 'id' => $invoice -> id]));
					} else return '';
				} else return $data['operation'];
			}
        ],
		
		[
            'attribute'=>'summa',	
			'label' => 'сумма',
			'format' => 'raw',
			'value' => function ($data) {
				if (isset($data['summa'])) {
					$value = Yii::$app->formatter->asCurrency($data['summa']);
					if ($data['invoice_id']) {
						$value = Html::tag('span', $value, ['class' => 'plus']);				
					} else {
						$value = Html::tag('span', '-'.$value, ['class' => 'minus']);				
					}
					return $value;
				} else {
					return '';
				}
				
			}
			
        ],
		
		[
            'attribute'=>'state',
			'label' => 'статус счета',	
			'format' => 'raw',
			'value' => function($data) {
				if (is_null($data['state'])) {
					$value = '';
				} else {
					if ($data['state'] == Invoice::STATE_NOPAID) {
						$value = 'не оплачен '.					
						Html::a('<i class="fa fa-credit-card" style="margin-left: 5px;"></i> ', ['/document/pay', 'id' => $data['id']], ['title' => 'Оплатить картой']);
						
					} else {
						
						$value = 'оплачен';
					}
				};
				return $value;
			},
			
        ],
	
	
		[
            'attribute'=>'invoice_id',
			'label' => 'счет',						
			'value' => function($data) {
				$model = Document::findOne($data['invoice_id']);				
				return $model?$model -> getCaption('счет №%number% от %created_at% на сумму %summa% р.'):'';
				//return  'Счет №'.$data['invoice_number'].' на сумму '.(int)$data['invoice_summa'].'руб.';
			},
//			'group'=>true,
        ],
		
		
		
		
		
/*		
		[
			'attribute'=>'payment_date',
		],
		[
			'attribute'=>'payment_summa',
		],
*/		
		
    ],	
	
]);

/* */
?>
    </div>
</div>

<?=$this->render('_filter', [
        'searchModel' => $searchModel,
	
]) 
?>		