backend/models/Import.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "adr_payments".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $date
 * @property integer $status
 * @property string $ptype
 * @property string $value
 * @property string $info
 *
 * @property User $user
 */
class Import extends \common\models\Import
{

}

common/models/Import.php
<?php

namespace common\models;

use Yii;
use common\models\EntityExt;

/**
 * This is the model class for table "adr_payments".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $date
 * @property integer $status
 * @property string $ptype
 * @property string $value
 * @property string $info
 *
 * @property User $user
 */
class Import extends \common\models\CObject
{


    public static function validateImportedFile($file){

        //$a = new Import();

        /*var_dump($a->captionTemplate());
        die();*/
        //$this->captionTemplate();


        $response["success"] = false;
        $response["message"] = 'unknown error';
        $availableMimeTypes = array(
            'application/vnd.ms-excel',
            'application/msexcel',
            'application/x-msexcel',
            'application/x-ms-excel',
            'application/x-excel',
            'application/x-dos_ms_excel',
            'application/xls',
            'application/x-xls',
            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        );
        $type = mime_content_type($file['tmp_name']);
        if(in_array($type, $availableMimeTypes)){
            if($file['size'] < 50 * 1024 * 1024){
                $response["success"] = true;
                $response["message"] = 'OK';
            }else{
                $response["message"] = 'too big';
            }
        }else{
            $response["message"] = 'wrong extension';
        }
        return $response;
    }

    public static function parseExcel($file){
        $inputFileType = \PHPExcel_IOFactory::identify($file['tmp_name']);
        $objReader = \PHPExcel_IOFactory::createReader($inputFileType);
        $objPHPExcel = $objReader->load($file['tmp_name']);
		
        foreach ($objPHPExcel->getWorksheetIterator() as $worksheet) {
	
            $arrayData[$worksheet->getTitle()] = $worksheet;
        };
		unset($objReader);
        return $arrayData;
    }
	
	public static function getData($file){
		$ppTypeId = DocumentType::byAlias('paymentorder') -> id;
		$invTypeId = DocumentType::byAlias('invoice') -> id;		
		$rIdList = array_keys(EntityExt::portal() -> requisiteList()); // Список реквизитов портала
		$result = [];
		$sheets = self::parseExcel($file);
		foreach ($sheets as $sheet) { 

			$highestRow = $sheet->getHighestRow();

			
			for ($row = 2; $row <= $highestRow; ++ $row) {
				$summ = $sheet -> getCellByColumnAndRow(1, $row) -> getValue(); // Сумма платежа
				if ($summ <= 0) continue;
				$dataRow = [];
				$pmDate = self::createDate($sheet -> getCellByColumnAndRow(0, $row)); // Дата платежа
				
				$invNumber = $sheet -> getCellByColumnAndRow(2, $row) -> getValue(); // Номер счета				
				$invDate = self::createDate($sheet -> getCellByColumnAndRow(3, $row)); // Дата счета				
				$ppNumber = $sheet -> getCellByColumnAndRow(4, $row) -> getValue(); // Номер платежки				
				$ppDate = self::createDate($sheet -> getCellByColumnAndRow(5, $row));	//  Дата платежки				
				
				$dataRow['pmDate'] = $pmDate;
				$dataRow['ppDate'] = $ppDate;
				$dataRow['summ'] = $summ;
				$dataRow['invNumber'] = $invNumber;
				$dataRow['invDate'] = $invDate;
				$dataRow['ppNumber'] = $ppNumber;				
				$dataRow['Payer'] = '';
				$dataRow['Recipient'] = '';	

				// Попробуем найти счет в базе с указанным номером и среди тех, которые выставлены порталом
				$inv = Document::find() -> andWhere(['doc_type_id' => $invTypeId, 'number' => $invNumber, 'owner_id' => $rIdList]) -> one(); /// TODO: Косяк! - не хочет искать по терминальному классу (Invoice)				
				////////////////////////////////////////////////////////////////////////////
				$dataRow['message'] = 'Ok.';
				$dataRow['messageType'] = 'message';
				
				if (!$pmDate) {					
					$dataRow['messageType'] = 'error';
					$dataRow['message'] = "Не указана дата поступления платежа - платеж не будет загружен";
				}
				
	
				if ($inv) { // счет найдет
					// Сравниваем сумму счета и платежа
					if ((int)$inv -> summa < (int)$summ) {
						$dataRow['messageType'] = 'notice';
						$dataRow['message'] = "Плата больше счета.";
					} else if ((int)$inv -> summa > (int)$summ) {
						$dataRow['messageType'] = 'notice';
						$dataRow['message'] = "Частичная оплата.";
					};
					/// Платежка
					// Попробуем найти платежку в базе

					
					$pp = Document::find() -> andWhere(['doc_type_id' => $ppTypeId, 'number' => $ppNumber, 'owner_id' => $inv -> recipient_id]) -> one();
					if ($pp) { // Нашлась
						$dataRow['messageType'] = 'notice';
						$dataRow['message'] = trim($dataRow['message']." Платеж уже существует в системе - будет обновлен");
					};
					
					$dataRow['Payer'] = $inv -> recipient -> getTitle().'<br>ИНН:'.$inv -> recipient -> inn;	
					$dataRow['Recipient'] = $inv -> owner -> getTitle().'<br>ИНН:'.$inv -> owner -> inn;	
					
				} else {
					$dataRow['messageType'] = 'error';
					$dataRow['message'] = "Счет не найден, платеж не будет загружен.";					
				};				
				

				
				////////////////////////////////////////////////////////////////////////////
				
				$result[] = $dataRow;
            }
        }
		return $result;
	}

	
	// Загрузка данных в систему. Возвращает этот же массив с комментариями по отработке
	public static function loadData($data) {
		$newCount = 0;
		$updatedCount = 0;
		if (!$data || !is_array($data))  {
			return false;
		} else {
			
			$ppTypeId = DocumentType::byAlias('paymentorder') -> id;
			$invTypeId = DocumentType::byAlias('invoice') -> id;		
			$rIdList = array_keys(EntityExt::portal() -> requisiteList()); // Список реквизитов портала
			$result = [];
			
			foreach($data as $dataRow) {
				$pmDate = $dataRow['pmDate'];
				$ppDate = $dataRow['ppDate'];
				$summ = $dataRow['summ'];
				$invNumber = $dataRow['invNumber'];
				$invDate = $dataRow['invDate'];
				$ppNumber = $dataRow['ppNumber'];	
				
				$inv = Document::find() -> andWhere(['doc_type_id' => $invTypeId, 'number' => $invNumber, 'owner_id' => $rIdList]) -> one(); 
				
				$dataRow['Recipient'] = $inv -> owner -> getTitle().'<br>ИНН:'.$inv -> owner -> inn;	
				$dataRow['Payer'] = $inv -> recipient -> getTitle().'<br>ИНН:'.$inv -> recipient -> inn;	
				$dataRow['message'] = 'Платеж добавлен';
				$dataRow['messageType'] = 'message';				
				// Попробуем найти счет в базе с указанным номером и среди тех, которые выставлены порталом
				
				$skip = false;
				////////////////////////////////////////////////////////////////////////////
							
				$dataRow['message'] = 'Платеж добавлен';
				$dataRow['messageType'] = 'message';
				
				if (!$pmDate) {					
					$dataRow['messageType'] = 'error';
					$dataRow['message'] = "Не указана дата поступления платежа - платеж не загружен";
					$skip = true;
				}
				
	
				if ($inv) { // счет найдет
					// Сравниваем сумму счета и платежа
					if ((int)$inv -> summa < (int)$summ) {
						$dataRow['messageType'] = 'notice';
						$dataRow['message'] = "Плата больше счета";
					} else if ((int)$inv -> summa > (int)$summ) {
						$dataRow['messageType'] = 'notice';
						$dataRow['message'] = "Частичная оплата";
					};
					
				
					/// Платежка
					// Попробуем найти загружаемую платежку в базе. Идентификация по номеру и плательшику
					$pp = Document::find() -> andWhere(['doc_type_id' => $ppTypeId, 'number' => $ppNumber, 'owner_id' => $inv -> recipient_id]) -> one();
					if ($pp) { // Нашлась
						
						$dataRow['messageType'] = 'notice';
						$dataRow['message'] = trim('Платеж обновлен');
					};
					
				} else {
					$dataRow['messageType'] = 'error';
					$dataRow['message'] = "Счет не найден, платеж не загружен.";					
					$skip = true;
				};				
				

			
			
				////////////////////////////////////////////////////////////////////////////
				
				$result[] = $dataRow;
				if ($skip ) continue;
				
				$rPortalId = $inv -> owner_id; // в платежке используются те же реквизиты портала, что и в счете
				
				/// Платежка
				// Попробуем найти платежку в базе
				$pp = Document::find() -> andWhere(['doc_type_id' => $ppTypeId, 'number' => $ppNumber, 'owner_id' => $inv -> recipient_id]) -> one();
				if (!$pp) { // Если не нашлась, то добавляем
					$pp = new Document();
					$pp -> doc_type_id = $ppTypeId;
					$pp -> number = $ppNumber;
					$pp -> owner_id = $inv -> recipient_id; // владелец платежки является плательщиком - это контрагент портала
					$pp -> recipient_id = $rPortalId;// получатель платежки является получателем платежа - это портал
					$newCount++;
				} else {
					$updatedCount++;
				}
				

				$pp -> created_at = $ppDate;
			
				$pp -> updated_at = $ppDate;
				$pp -> order_id = $inv -> order_id;
				$pp -> porder_id = $inv -> porder_id;
				$pp -> address_id = $inv -> address_id;
				$pp -> summa = $inv -> summa;

				$pp -> save();
							

				$inv_id = $inv -> id; 
				$inv = Invoice::findOne([$inv_id]) ;
				$inv -> payment($pp, ['date' => $pmDate, 'loaded_at' => Entity::dbNow()]); // создаем оплату по платежке
				
				
			}
			$message = '';
			if ($newCount > 0) {
				$message = $message.'Добавлено платежей: '.$newCount.'<br>';	
			};
			if ($updatedCount > 0) {
				$message = $message.'Обновлено платежей: '.$updatedCount.'<br>';	
			};
			
			
			if ($updatedCount + $newCount > 0) {
				Yii::$app->session->setFlash('success', $message);
			} else {
				Yii::$app->session->setFlash('error', "Ни одного платежа не закружено");
			}
			
			return $result;
			
		}		
	}
	
	protected static function createDate($cell, $format = 'd.m.Y') {
		
		$result = NULL;
		if ($cell) {
			$value = $cell->getValue();
			if(\PHPExcel_Shared_Date::isDateTime($cell)) {				
				$result = date($format, \PHPExcel_Shared_Date::ExcelToPHP($value)); 
			}

		}
		return $result;
	}
	
    public static function compareToDbData($sheets){

		$ppTypeId = DocumentType::byAlias('paymentorder') -> id;
		$invTypeId = DocumentType::byAlias('invoice') -> id;

frontend/models/Import.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "adr_payments".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $date
 * @property integer $status
 * @property string $ptype
 * @property string $value
 * @property string $info
 *
 * @property User $user
 */
class Import extends \common\models\Import
{

}

backend/controllers/ImportController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Payment;
use backend\models\Import;
use backend\models\PaymentSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PaymentController implements the CRUD actions for Payment model.
 */
class ImportController extends PaymentController
{
    /**
     * @inheritdoc
     */
    public function beforeAction($action)
    {
        // ...set `$this->enableCsrfValidation` here based on some conditions...
        // call parent method that will check CSRF if such property is true.

            # code...
            //$this->enableCsrfValidation = false;

        return parent::beforeAction($action);
    }

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Payment models.
     * @return mixed
     */
    public function actionIndex()
    {
        $data = [];
		$res = false;
        if(Yii::$app->request->isPost){
            /** Request method is POST, check file*/
            if(!isset($_FILES['excel'])) return;
            $response = Import::validateImportedFile($_FILES['excel']);  /** Validating file */
            if($response['success']){
                $sheets = Import::parseExcel($_FILES['excel']); /** Parsing file and get array with result */								
                //$data = Import::compareToDbData($sheets); /** Comparing to db data and returns array for table to display */
				$res = Import::compareToDbData($sheets); /** Comparing to db data and returns array for table to display */
            }

        }
	
        return ($res)? $this->redirect(array('payment/index')):$this->render('index', array("data" => []));


    }
    public function actionOutcome()
    {
        $data = [];
        if(Yii::$app->request->isPost){
	
			return "Функция временно откючена";
            /** Request method is POST, check file*/
			
            if(!isset($_FILES['excel'])) return;
            $response = Import::validateImportedFile($_FILES['excel']);  /** Validating file */

            if($response['success']){
                $sheets = Import::parseExcel($_FILES['excel']); /** Parsing file and get array with result */

                $data = Import::compareToDbDataOutcome($sheets); /** Comparing to db data and returns array for table to display */
            }
        }
        return $this->render('outcome', array("data" => $data));


    }



    /**
     * Creates a new Payment model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
       // echo "<pre>", print_r($_POST); die();
        if(isset($_POST['data'])){
            Import::importAndModify();
        }

        $this->redirect(array('payment/index'));

    }

    public function actionCreateOutcome()
    {

        if(isset($_POST['data'])){
            Import::importAndModifyOutcome();
        }

        $this->redirect(array('payment/index'));

    }


}

frontend/views/admin/import/___outcome.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\AddressSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */


$this->title = 'Импорт исходящих платежей';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="import-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php



    $i=0; //count records for insert
    if(count($data)) : ?>
        <?php //echo "<pre>", print_r($data); die(); ?>
        <form action="<?php echo Yii::$app->urlManager->createUrl(['import/create-outcome']);?>" method="POST">
            <input type="hidden" name="_csrf-backend" value="<?=Yii::$app->request->getCsrfToken()?>" />
            <table class="table">
                <th>Дата платежа</th>
                <th>Сумма</th>
                <th>Номер заказа</th>
                <th>Контрагент</th>
                <?php foreach ( $data as $line): ?>
                    <?php
                    $class = 'regular';
                    $save = true;
                    $query = $line["query_result"];
                    $payment_info = $line["payment_info"];
                   // echo "<pre>", print_r($line); //die();
                    if($query == false || (int)$line[2] == 0 || (int)$query['customer_id'] == 0){
                        $save = false;
                        $class = 'not-found';
                    }

                    /** Cмотрим по другим платежам (по этому заказу
                     *  сравниваем даты и номера поручений
                     */
                    if(is_array($payment_info) && count($payment_info) > 0){
                        //$save = true;
                        foreach($payment_info as $payment){

                            if($payment['date'] == date("Y-m-d H:i:s", strtotime($line[4])) && $payment['number'] == (int)trim($line[3])){
                                $save = false; // комбинация с одинаковым пользователем, одинаковой датой и номером - найдена
                                $class = 'same-detected';
                            }
                        }
                    }

                    ?>
                    <tr class="<?=$class;?>">
                        <?php if($save): ?>
                            <input type="hidden" name="data[<?=$i?>][payment][date]" value="<?=date("Y-m-d H:i:s", strtotime($line[0])); ?>"/>
                            <input type="hidden" name="data[<?=$i?>][payment][value]" value="<?=(int)$line[1];?>"/>
                            <input type="hidden" name="data[<?=$i?>][document][order_id]" value="<?=(int)$line[2];?>"/>
                            <input type="hidden" name="data[<?=$i?>][payment][order_id]" value="<?=(int)$line[2];?>"/>
                            <input type="hidden" name="data[<?=$i?>][document][number]" value="<?=(int)$line[3];?>"/>
                            <input type="hidden" name="data[<?=$i?>][document][date]" value="<?=date("Y-m-d H:i:s", strtotime($line[4]));?>"/>
                            <input type="hidden" name="data[<?=$i?>][payment][user_id]" value="<?=$query['customer_id'];?>"/>

                        <?php endif; ?>
                        <td>
                            <?=date("Y-m-d H:i:s", strtotime($line[0])); ?>

                        </td>
                        <td>
                            <?=$line[1];?>
                        </td>
                        <td>
                            <?=$line[2];?>
                        </td>
                        <td><?php
                            if(isset($query['username'])){
                                echo $query['username'];
                            }else{
                                echo "-";
                            }
                            ?></td>

                        <?php if(!empty($class)){
                            switch ($class){
                                case 'not-found': echo '<td>Платеж не найден</td>'; break;
                                case 'same-detected': echo '<td>Cчёт оплачен</td>'; break;
                            }
                        } ?>

                        <?php $i++; ?>

                    </tr>
                <?php endforeach; ?>
            </table>
            <button type="submit" class="btn btn-success">Сохранить</button>
        </form>
    <?php else: ?>
        <form action="" method="POST" enctype="multipart/form-data">
            <div class="form-group">
                <label for="file">Excel файл</label>
                <input type="file" name="excel" class="form-control" id="file">
                <input type="hidden" name="_csrf-backend" value="<?=Yii::$app->request->getCsrfToken()?>" />
            </div>
            <button type="submit" class="btn btn-success">Загрузить</button>
        </form>
    <?php endif; ?>
</div>

frontend/views/admin/import/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\AddressSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */


$this->title = 'Импорт входящих платежей';
$this->context -> h1 = $this->title;
$this->params['breadcrumbs'][] = $this->title;



?>

    <?php
	$i = 0;
    if($data && is_array($data) && count($data)) : ?>
    <form action="<?php echo Yii::$app->urlManager->createUrl(['admin/import/load']);?>" method="POST">
        <input type="hidden" name="_csrf-backend" value="<?=Yii::$app->request->getCsrfToken()?>" />
		
        <table class="table">
		<tr class="head">
            <th>Дата платежа</th>
            <th>Сумма</th>
            <th>Счет</th>            
			<th>П/п</th>            
			<th>Плательщик</th>
			<th>Получатель</th>
			 <th>Информация</th>
		</tr>	
		
		
        <?php foreach ( $data as $line): 
		
					
			$class = isset($line['messageType'])?('line-'.$line['messageType']):false;
			$class = $class?' class="'.$class.'"':'';
			?>
			

		<tr<?=$class?>>
                <td>
                    <?=$line['pmDate']; ?>
					<?php if ($mode == 'view'):?>
					<input type="hidden" name="data[<?=$i?>][pmDate]" value="<?=$line['pmDate']?>"/>
					<?php endif?>
                </td>
                <td>
                    <?=Yii::$app -> formatter -> asCurrency($line['summ'])?>
					<?php if ($mode == 'view'):?>
					<input type="hidden" name="data[<?=$i?>][summ]" value="<?=$line['summ']?>"/>
					<?php endif?>
                </td>
                <td>
                    <?='№'.$line['invNumber'].'<br>от '.$line['invDate'];?>
					<?php if ($mode == 'view'):?>
					<input type="hidden" name="data[<?=$i?>][invNumber]" value="<?=$line['invNumber']?>"/>
					<input type="hidden" name="data[<?=$i?>][invDate]" value="<?=$line['invDate']?>"/>
					<?php endif?>
                </td>

				<td>
                    <?='№'.$line['ppNumber'].'<br>от '.$line['ppDate'];?>
					<?php if ($mode == 'view'):?>
					<input type="hidden" name="data[<?=$i?>][ppNumber]" value="<?=$line['ppNumber']?>"/>
					<input type="hidden" name="data[<?=$i?>][ppDate]" value="<?=$line['ppDate']?>"/>
					<?php endif?>
                </td>
                
				<td>
                    <?=$line['Payer'];?>					
                </td>
				<td>
                    <?=$line['Recipient'];?>										
                </td>
				<td>	
					<?=$line['message']?>
					
				</td>
				
                <?php $i++; ?>

            </tr>
        <?php endforeach; ?>
        </table>
		<?php if ($mode == 'view'):?>
        <button type="submit" class="public-address-button" style="margin-bottom: 20px;">Загрузить</button>
		<?php endif ?>
		<input type="hidden" name="_csrf-backend" value="<?=Yii::$app->request->getCsrfToken()?>" />
    </form>
    <?php endif; ?>
	
	
		<div class="content">
		Выберите файл MS Excel с платежами порталу, которые необходимо загрузить в систему.
		</div>
        <form enctype="multipart/form-data" action="<?php echo Yii::$app->urlManager->createUrl(['admin/import']);?>" method="POST">
            <div class="form-group">                
                <input type="file" onchange="form.submit();" name="excel" class="form-control" id="file">
                <input type="hidden" name="_csrf-backend" value="<?=Yii::$app->request->getCsrfToken()?>" />
            </div>            
        </form>
 

frontend/views/admin/import/out.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\AddressSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */


$this->title = 'Импорт исходящих платежей';
$this->context -> h1 = $this->title;
$this->params['breadcrumbs'][] = $this->title;


?>

    <?php
	$i = 0;
    if($data && is_array($data) && count($data)) : ?>
    <form action="<?php echo Yii::$app->urlManager->createUrl(['admin/import/load']);?>" method="POST">
        <input type="hidden" name="_csrf-backend" value="<?=Yii::$app->request->getCsrfToken()?>" />
		
        <table class="table">
		<tr class="head">
            <th>Дата платежа</th>
            <th>Сумма</th>
			<th>П/п</th>            
            <th>Плательщик</th>            
			<th>Получатель</th>            
			 <th>Информация</th>
		</tr>	
		
		
        <?php foreach ( $data as $line): 
		
					
			$class = isset($line['messageType'])?('line-'.$line['messageType']):false;
			$class = $class?' class="'.$class.'"':'';
			?>
			
		<input type="hidden" name="data[out]" value="out"/>
		<tr<?=$class?>>
                <td>
                    <?=$line['pmDate']; ?>
					<?php if ($mode == 'view'):?>
					<input type="hidden" name="data[<?=$i?>][pmDate]" value="<?=$line['pmDate']?>"/>
					<?php endif?>
                </td>
                <td>
                     <?=Yii::$app -> formatter -> asCurrency($line['summ'])?>
					<?php if ($mode == 'view'):?>
					<input type="hidden" name="data[<?=$i?>][summ]" value="<?=$line['summ']?>"/>
					<?php endif?>
                </td>
                <td>
                    <?='№'.$line['ppNumber'].'<br>от '.$line['ppDate'];?>
					<?php if ($mode == 'view'):?>
						<input type="hidden" name="data[<?=$i?>][ppNumber]" value="<?=$line['ppNumber']?>"/>
						<input type="hidden" name="data[<?=$i?>][ppDate]" value="<?=$line['ppDate']?>"/>
					<?php endif?>
                </td>
            
				<td>
                    <?=$line['payer'];?>
                </td>   
				<td>
                    <?=$line['recipient'];?>
					<?php if ($mode == 'view'):?>
						<input type="hidden" name="data[<?=$i?>][recipient]" value="<?=$line['recipientId']?>"/>
					<?php endif?>
                </td>    				
				<td>	
					<?=$line['message']?>
					
				</td>
				
                <?php $i++; ?>

            </tr>
        <?php endforeach; ?>
        </table>
		<?php if ($mode == 'view'):?>
        <button type="submit" class="public-address-button" style="margin-bottom: 20px;">Загрузить</button>
		<?php endif ?>
		<input type="hidden" name="_csrf-backend" value="<?=Yii::$app->request->getCsrfToken()?>" />
    </form>
    <?php endif; ?>
	
	
		<div class="content">
		Выберите файл MS Excel с платежами порталу, которые необходимо загрузить в систему.
		</div>
        <form enctype="multipart/form-data" action="<?php echo Yii::$app->urlManager->createUrl(['admin/import/out']);?>" method="POST">
            <div class="form-group">                
                <input type="file" onchange="form.submit();" name="excel" class="form-control" id="file">
                <input type="hidden" name="_csrf-backend" value="<?=Yii::$app->request->getCsrfToken()?>" />
            </div>            
        </form>
 